### PR TITLE
reworked simpleCapAlloc

### PR DESCRIPTION
**Pull request by gypsephi**
reworked SimpleCapAlloc as mentioned in #172.
Do you have a better solution than specifyin the template arguments in both init.cc and cxx-support?

Tested with QEMU and IHK

### CODE REVIEW

**Comment by kubanrob** [comment]
> Do you have a better solution than specifying the template arguments in both init.cc and cxx-support?

We could have a typedef in a common headerfile (`runtime/capAlloc.hh`?). Something like:
```
typedef mythos::SimpleCapAlloc< mythos::init::APP_CAP_START
  , mythos::init::SIZE-mythos::init::APP_CAP_START> cap_alloc_t;
extern cap_alloc_t capAlloc;
```

**Review by kubanrob — COMMENTED** [review]
I think it wouldn't be a bad idea to keep the original simple allocator in order to avoid somebody re-implementing it.

Otherwise it seems like a sensible implementation. Builds and runs on my machine.

**Comment by gypsephi** [comment]
> > Do you have a better solution than specifying the template arguments in both init.cc and cxx-support?
> 
> We could have a typedef in a common headerfile (`runtime/capAlloc.hh`?). Something like:
> 
> ```c++
> typedef mythos::SimpleCapAlloc< mythos::init::APP_CAP_START,
>   mythos::init::SIZE-mythos::init::APP_CAP_START> cap_alloc_t;
> extern cap_alloc_t capAlloc;
> ```

okay...

**Comment by gypsephi** [comment]
> I think it wouldn't be a bad idea to keep the original simple allocator in order to avoid somebody re-implementing it.
> 
> Otherwise it seems like a sensible implementation. Builds and runs on my machine.
the old allocator has no benefits, so we should get rid of it. If somebody runs apps with it, they can still use the old mythos master commit. Additionally updating an app accordingly isn't that hard.

**Comment by kubanrob** [comment]
> the old allocator has no benefits, so we should get rid of it.

It's lock-free and has small overhead for serial programms ... yeah you are right, we probably can get rid of it. I'm not super attached :)

**Review by kubanrob — APPROVED** [review]
See previous comments.

**Comment by gypsephi** [comment]
implemented cap_alloc_t
tested with qemu and ihk

**Pull request merged**
